# Generated by Django 6.0.1 on 2026-01-21 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_alter_servidor_icono'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='referencia2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servidor',
            name='referncia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='servidor',
            name='servicio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
