# Generated by Django 6.0.1 on 2026-01-21 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_servidor_referencia2_servidor_referncia_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servidor',
            old_name='referncia',
            new_name='referencia',
        ),
    ]
