# Generated by Django 6.0.1 on 2026-01-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0006_rename_referncia_servidor_referencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reportes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ip', models.GenericIPAddressField(protocol='IPv4')),
                ('servicio', models.IntegerField(blank=True, null=True)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('referencia2', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('fecha_levanta', models.DateTimeField(blank=True, null=True)),
                ('quien_levanta', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
