# Generated by Django 6.0.1 on 2026-01-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_reportes'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportes',
            name='observacion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
