# Generated by Django 6.0.1 on 2026-01-22 18:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_reportes_personal_sitio_reportes_telefono_contacto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportes',
            name='referencia',
        ),
        migrations.RemoveField(
            model_name='reportes',
            name='referencia2',
        ),
        migrations.AddField(
            model_name='reportes',
            name='que_cayo',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reportes',
            name='quien_levanta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quien_levanta', to=settings.AUTH_USER_MODEL),
        ),
    ]
