# Generated by Django 6.0.1 on 2026-01-22 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_remove_reportes_referencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportes',
            name='enlace',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
