# Generated by Django 6.0.1 on 2026-01-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_reportes_enlace'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportes',
            name='estatus',
            field=models.CharField(choices=[(1, 'Activo'), (2, 'Cerrado')], default=1, max_length=1),
        ),
    ]
