# Generated by Django 6.0.1 on 2026-01-22 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_reportes_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportes',
            name='estatus',
            field=models.IntegerField(choices=[(1, 'Activo'), (2, 'Cerrado')], default=1),
        ),
    ]
