# Generated by Django 6.0.1 on 2026-01-23 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_alter_reportes_estatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportes',
            name='observaciones_finales',
            field=models.TextField(blank=True, null=True),
        ),
    ]
