# Generated by Django 6.0.1 on 2026-01-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0014_reportes_observaciones_finales'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='proveedor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='servidor',
            name='servicio',
            field=models.CharField(blank=True, null=True),
        ),
    ]
