# Generated by Django 6.0.1 on 2026-01-30 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0015_servidor_proveedor_alter_servidor_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='servidor',
            name='puerto',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
